#!/bin/sh

JNCCLIENT_HOME=/usr/share/jncclient
NCDIAG_CMD=$JNCCLIENT_HOME/ncdiag

case "$1" in
    "tunnel" )
        $NCDIAG_CMD -t | grep -q Established;
        ;;
    "service" )
        ps -C ncsvc > /dev/null
        ;;
    "dhcp" )
        [ `ip link | grep -E 'tun[0-9]*:' | wc -l ` -ge 1 ]
        ;;
    * )
        echo "Syntax: `basename $0` <tunnel|service|dhcp>"
        exit 1
        ;;
esac
